Update certificates_retiring_certificates.md
mrets/Help pull request #61
Opened 2023-12-15 18:57 UTC by markmrets

2023-12-20 16:16 UTC, BryanGower requested changes
The link should be updated: https://mrets.github.io/Help/certificate_retirements

2023-12-20 16:17 UTC, BryanGower commented
@markmrets The link needs to be updated.

2023-12-20 16:55 UTC, markmrets reviewed
fixed the link

2023-12-28 21:35 UTC, BryanGower approved these changes

2023-12-28 21:35 UTC, merged